GRANT CONNECT ON DATABASE ddl_test TO "derpibooru-user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "derpibooru-user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO "derpibooru-user";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "derpibooru-user";
ALTER TABLE tag OWNER TO "derpibooru-user";
ALTER SEQUENCE tag_id_seq OWNER TO "derpibooru-user";
